### ISSUE TITLE
White and grey screen upon opening of TI-84 Plus 8rom

### ISSUE THREAD

**Issue by randoslap** [pbfy0/nspire-z80#1]
Running Ndless 4.4, upon opening TI-84 Plus rom, white screen with grey border appears, and the system hangs. Reset is required to bring it back up. TI-Nspire CX HW-J

As an aside, I've also had difficulty compiling, most likely my problem, but other ndless projects have compiled fine so far.

Cheers

**Comment by pbfy0** [comment]
I haven't updated the makefile in forever in the version that's available online, so it probably won't compile with new versions of ndless. Have you tried pressing the home button? It's mapped to on and sometimes required to make the calculator actually start. Does pressing escape get you out of the emulator, or is it actually totally frozen?

**Comment by randoslap** [comment]
Well I sure look like a fool. I could have sworn that it was a full hang, but I was wrong. Escape did the trick. The rom however still didn't work, but from that point I deduced that my rom file was most likely the culprit, swapped it out with another one, (an 84 SE), and it worked.

Thanks for helping me bumble my way through to a solution!

**Comment by pbfy0** [comment]
I certainly didn't do any exhaustive testing; I only tested it with a couple roms. Does the rom work in another emulator?

**Comment by randoslap** [comment]
Nice job on finding the actual kink in the works, yeah the original rom did work in another emulator, so it took me a bit to consider that as the factor. Funny enough, I didn't specifically need the 84 plus, it's just what I had on hand at the time, but thanks for updating the makefile, It'll be useful for making some slight adjustments to keybindings and such.
