### ISSUE TITLE
The device freezes upon doing anything

### ISSUE THREAD

**Issue by coreycusick** [pbfy0/nspire-z80#4]
My Ti-Nspire CX CAS freezes when doing any math, like 8+1, and there are lines on the screen, help!

**Comment by pbfy0** [comment]
What exact kind of ROM are you using? Could you send me a picture of the lines so I can get a better idea of the problem?

**Comment by coreycusick** [comment]
I’m using a ti 84 plus se, os 2.5.5, it appears to happen when the cpu is being used for anything besides typing numbers, it happens every time I press enter

**Comment by pbfy0** [comment]
The lines are a HW-W issue. That's an easy fix. I'm not sure about the freezing, though. What nspire OS version are you using? I'll try running it in the emulator with that version.

**Comment by coreycusick** [comment]
4.5.0.1180

**Comment by pbfy0** [comment]
I think I've fixed the issue in v0.10.1. Download the new version and give it a try.

**Comment by coreycusick** [comment]
Fantastic, it works wonderfully, no more lines, and no more freezing, Thanks!
