### ISSUE TITLE
Doesn't work on classic nspire ?

### ISSUE THREAD

**Issue by Syrusse** [pbfy0/nspire-z80#5]
Hello, 
I've just tried this awesome emulator on my "new" nspire, and it seems that it's not working (at least for me) on my clickpad cas nspire, I mean, after launching the file named "nspire-z80", the extenstion .8rom is added but when I'm launching my rom, it says that it cannot read this type of file extension.
That's why I'm asking if a classic nspire compatibility is worked on or not ?
Thanks in advance :)

**Comment by Syrusse** [comment]
Ooooh I see, never mind, tbh I need it for Friday, and it's totally impossible, and it's probably not worth it to spend your time for a few persons, thank you very much for your answer though, I can't code so it's not possible for me to port it to greyscale nspire, oh and by the way, your video player is awesome :3 
Have a nice day !

**Comment by theperson50** [comment]
I'd love to try and port this to a greyscale nspire, but I'll have to learn this coding first
Edit: also, my greyscale nspire does recognise the .8rom extension, but it freezes after loading it
