### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by eleding24** [pbfy0/nspire-z80#8]
I can't install a rom.

When I open up the rom it says:

File document is not supported

**Comment by pbfy0** [comment]
Did you run nspire-z80.tns once beforehand? It needs to be run to register the file extension with Ndless.

**Comment by eleding24** [comment]
Yeah

**Comment by eleding24** [comment]
Though, I think I fixed the problem. I downloaded the file multiple times and put in the (1) file and not the original name file. After I changed the nspire-z80(1).tns file to nspire-z80.tns, it solved the problem.

**Comment by eleding24** [comment]
Though, I am still wondering:

How do you install apps into the ti 84 emulator?
