### ISSUE TITLE
Apps

### ISSUE THREAD

**Issue by eleding24** [pbfy0/nspire-z80#9]
Is there anyway to install apps to the TI 84 SE Emulator?

**Comment by hacker1024** [comment]
Did you ever work this out?

**Comment by hding24** [comment]
Yes. In order to install apps you have to use wabbitemu and install the apps you want to the emulator. Afterwards, you can then download the copy of that rom file with your apps installed and install it into your calculator.

**Comment by hacker1024** [comment]
Awesome, thanks.
